UrlShortener/UrlShortener/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('urlgen.urls')),
]

UrlShortener/urlgen/urls.py
from django.urls import path, re_path
from . import views

app_name = 'urlgen'

urlpatterns = [
    path('', views.home, name = "home"),
    path('error', views.error, name = "error"),   
    path('<slug:detail>', views.bigredirect, name = "bigredirect"),  
    path('redirect/<slug:detail>', views.redirect, name = "redirect"),   
]

UrlShortener/urlgen/models.py
from django.db import models
# Create your models here.

class url(models.Model):
    big_url = models.URLField(max_length=200)
    short_url = models.TextField(max_length=200, unique = True)

    def __str__(self):
        return self.short_url
    

UrlShortener/urlgen/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, reverse, redirect
import string 
import random
from .models import url

# Create your views here.
def home(request):
    if request.method == 'POST':
        urltest = None
        try:
            bigurl = request.POST.get('bigurl')
            if bigurl[0:5]!='https':
                bigurl = 'https://'+bigurl
            shortcut = request.POST.get('preferred') # None if empty
            if not shortcut:
                if url.objects.filter(big_url = bigurl).exists():
                    urlobj = url.objects.filter(big_url = bigurl)[0]
                    return HttpResponseRedirect('redirect/{0}'.format(urlobj.short_url))
            else:
                if not url.objects.filter(short_url = shortcut).exists():
                    url.objects.create(big_url = bigurl, short_url = shortcut)
                    urltest = url.objects.get(short_url = shortcut)
                    urltest.full_clean()
                    return HttpResponseRedirect('redirect/{0}'.format(shortcut))
                else:
                    print(shortcut)
                    return render(request, 'urlgen/home.html', {'error':'The path has already been taken'})
            notunique = True
            while(notunique):
                res = ''.join(random.choices(string.ascii_uppercase + string.digits, k = 5)) 
                if url.objects.filter(short_url = res).exists():
                    pass
                else:
                    shortcut = res
                    break
            url.objects.create(big_url = bigurl, short_url = shortcut)
            urltest = url.objects.get(short_url = shortcut)
            urltest.full_clean()
            return HttpResponseRedirect('redirect/{0}'.format(shortcut))
        except:
            urltest.delete()
            return render(request, 'urlgen/home.html', {'error':'Not an URL'})
    return render(request, 'urlgen/home.html')

def redirect(request, detail):
    shorturl = detail
    urlobj = url.objects.get(short_url = shorturl)
    return render(request, 'urlgen/redirect.html', {'url':urlobj})

def error(request):
    return render(request, 'urlgen/error.html')

def bigredirect(request, detail):
    if not url.objects.filter(short_url = detail).exists():
        return HttpResponseRedirect(reverse('urlgen:error'))
    else:
        urlobj = url.objects.get(short_url = detail)
        return HttpResponseRedirect("{0}".format(urlobj.big_url))

UrlShortener/templates/urlgen/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>Short URL</title>
    <link href={% static 'urlgen/CSS/base.css' %} rel='stylesheet' type='text/css'>
</head>
<body>
    <div class = "container">
        <div class="title">
            <a class="nounderline" href={% url 'urlgen:home' %}><h1><span class="a1">URL</span> <span class="a2">Sho</span><span class="a3">rte</span><span class="a4">ner</span></h1></a>
        </div>
        <div class="search">
            {% block content %}
            {% endblock %}
        </div>
        <div class = "footer">
            <a class="link" target="_blank" href="https://github.com/Sid200026/">Made by Siddharth Singha Roy</a>
        </div>
    </div>
</body>
</html>

UrlShortener/templates/urlgen/error.html
{% extends 'urlgen/base.html'%}
{% block content %}
<h1 class="error">Oops... NO such URL exists</h1>
<a class="nounderline" href={% url 'urlgen:home' %}><h1>If you want to generate a shortened URL, Click here</h1></a>
{% endblock %}

UrlShortener/templates/urlgen/home.html
{% extends 'urlgen/base.html'%}
{% block content %}
{% if error %}
    <h2 class="error">{{error}}</h2>
{% endif %}
<form method='POST'>
    {% csrf_token %}
    <div class="search">
        <label class="headlabel" for="bigurl">Enter the URL to be shortened</label>
        <input type = "text" class="bigurl noSelect" placeholder = "Enter an URL...." name = "bigurl" required></input>
        <label class="headlabel" for="bigurl">Preferred URL path</label>
        <input type = "text" class="bigurl noSelect result" placeholder = "Preferred URL path name" name = "preferred"></input>
        <input type = "submit" value = "Shorten URL" class="submit noSelect"></input>
    </div>
</form>
{% endblock %}

UrlShortener/templates/urlgen/redirect.html
{% extends 'urlgen/base.html'%}
{% block content %}
<form method='POST'>
    {% csrf_token %}
    <div class="search">
        <label class="headlabel" for="bigurl">Actual URL</label>
        <input type = "text" value = {{url.big_url}} class="bigurl noSelect" placeholder = "Enter an URL...." name = "bigurl" required></input>
        <label class="headlabel" for="bigurl">Shortened URL</label>
        <input type = "text" value = {{url.short_url}} class="bigurl noSelect result" placeholder = "Result" name = "shortURL" readonly></input>
        <a href={% url 'urlgen:home' %}><input type = "button" value = "Shorten Another URL" class="submit noSelect"></input></a>
    </div>
</form>
{% endblock %}